# -*- coding: utf-8 -*-
"""向本地数据库批量灌入四六级高频单词。
生成 INSERT SQL 到 seed_words.sql，再通过 psql 执行。
字段：word / phonetic / definition / part_of_speech / difficulty_level
"""
import io

# (word, phonetic, definition, part_of_speech, difficulty)
WORDS = [
    # ===== A =====
    ("ability", "əˈbɪləti", "n. 能力；才能", "noun", "EASY"),
    ("abroad", "əˈbrɔːd", "adv. 在国外；到国外", "adverb", "EASY"),
    ("absent", "ˈæbsənt", "adj. 缺席的；不在场的", "adj", "EASY"),
    ("absorb", "əbˈzɔːrb", "v. 吸收；使专心", "verb", "MEDIUM"),
    ("abstract", "ˈæbstrækt", "adj. 抽象的 n. 摘要", "adj", "MEDIUM"),
    ("academic", "ˌækəˈdemɪk", "adj. 学术的 n. 学者", "adj", "MEDIUM"),
    ("accent", "ˈæksent", "n. 口音；重音", "noun", "EASY"),
    ("access", "ˈækses", "n. 通道；访问权 v. 访问", "noun", "MEDIUM"),
    ("accident", "ˈæksɪdənt", "n. 事故；意外", "noun", "EASY"),
    ("accompany", "əˈkʌmpəni", "v. 陪伴；伴随", "verb", "MEDIUM"),
    ("accomplish", "əˈkɑːmplɪʃ", "v. 完成；实现", "verb", "MEDIUM"),
    ("accurate", "ˈækjərət", "adj. 准确的；精确的", "adj", "MEDIUM"),
    ("accuse", "əˈkjuːz", "v. 指责；控告", "verb", "MEDIUM"),
    ("achieve", "əˈtʃiːv", "v. 达到；实现", "verb", "EASY"),
    ("acknowledge", "əkˈnɑːlɪdʒ", "v. 承认；致谢", "verb", "MEDIUM"),
    ("acquire", "əˈkwaɪər", "v. 获得；习得", "verb", "MEDIUM"),
    ("adapt", "əˈdæpt", "v. 适应；改编", "verb", "MEDIUM"),
    ("adequate", "ˈædɪkwət", "adj. 足够的；适当的", "adj", "MEDIUM"),
    ("adjust", "əˈdʒʌst", "v. 调整；适应", "verb", "MEDIUM"),
    ("admire", "ədˈmaɪər", "v. 钦佩；赞赏", "verb", "EASY"),
    ("admit", "ədˈmɪt", "v. 承认；准许进入", "verb", "EASY"),
    ("adopt", "əˈdɑːpt", "v. 采用；收养", "verb", "MEDIUM"),
    ("advance", "ədˈvæns", "v. 前进；进展 n. 进步", "verb", "MEDIUM"),
    ("advantage", "ədˈvæntɪdʒ", "n. 优势；有利条件", "noun", "EASY"),
    ("adventure", "ədˈventʃər", "n. 冒险；奇遇", "noun", "EASY"),
    ("advertise", "ˈædvərtaɪz", "v. 做广告；宣传", "verb", "MEDIUM"),
    ("advocate", "ˈædvəkeɪt", "v. 提倡 n. 拥护者", "verb", "HARD"),
    ("affect", "əˈfekt", "v. 影响；感动", "verb", "MEDIUM"),
    ("afford", "əˈfɔːrd", "v. 负担得起；提供", "verb", "EASY"),
    ("agency", "ˈeɪdʒənsi", "n. 机构；代理处", "noun", "MEDIUM"),
    ("aggressive", "əˈɡresɪv", "adj. 好斗的；进取的", "adj", "MEDIUM"),
    ("agriculture", "ˈæɡrɪkʌltʃər", "n. 农业", "noun", "MEDIUM"),
    ("aim", "eɪm", "n. 目标 v. 瞄准", "noun", "EASY"),
    ("alarm", "əˈlɑːrm", "n. 警报；闹钟", "noun", "EASY"),
    ("alcohol", "ˈælkəhɔːl", "n. 酒精；酒", "noun", "EASY"),
    ("alter", "ˈɔːltər", "v. 改变；更改", "verb", "MEDIUM"),
    ("alternative", "ɔːlˈtɜːrnətɪv", "n. 替代方案 adj. 可替代的", "noun", "MEDIUM"),
    ("ambition", "æmˈbɪʃn", "n. 雄心；抱负", "noun", "MEDIUM"),
    ("analyze", "ˈænəlaɪz", "v. 分析", "verb", "MEDIUM"),
    ("ancient", "ˈeɪnʃənt", "adj. 古代的；古老的", "adj", "MEDIUM"),
    ("announce", "əˈnaʊns", "v. 宣布；宣告", "verb", "MEDIUM"),
    ("anxiety", "æŋˈzaɪəti", "n. 焦虑；忧虑", "noun", "MEDIUM"),
    ("apologize", "əˈpɑːlədʒaɪz", "v. 道歉", "verb", "EASY"),
    ("apparent", "əˈpærənt", "adj. 明显的；表面的", "adj", "MEDIUM"),
    ("appeal", "əˈpiːl", "v. 呼吁；吸引 n. 吸引力", "verb", "MEDIUM"),
    ("appreciate", "əˈpriːʃieɪt", "v. 欣赏；感激", "verb", "EASY"),
    ("approach", "əˈproʊtʃ", "v. 接近 n. 方法；途径", "verb", "MEDIUM"),
    ("appropriate", "əˈproʊpriət", "adj. 适当的；恰当的", "adj", "MEDIUM"),
    ("approve", "əˈpruːv", "v. 批准；赞成", "verb", "MEDIUM"),
    ("argue", "ˈɑːrɡjuː", "v. 争论；主张", "verb", "EASY"),
    ("arise", "əˈraɪz", "v. 出现；产生", "verb", "MEDIUM"),
    ("arrange", "əˈreɪndʒ", "v. 安排；整理", "verb", "EASY"),
    ("arrest", "əˈrest", "v. 逮捕 n. 逮捕", "verb", "MEDIUM"),
    ("artificial", "ˌɑːrtɪˈfɪʃl", "adj. 人造的；人工的", "adj", "MEDIUM"),
    ("aspect", "ˈæspekt", "n. 方面；外观", "noun", "MEDIUM"),
    ("assess", "əˈses", "v. 评估；估价", "verb", "MEDIUM"),
    ("assign", "əˈsaɪn", "v. 分配；指派", "verb", "MEDIUM"),
    ("assist", "əˈsɪst", "v. 帮助；协助", "verb", "MEDIUM"),
    ("associate", "əˈsoʊʃieɪt", "v. 联系；联想", "verb", "MEDIUM"),
    ("assume", "əˈsuːm", "v. 假设；承担", "verb", "MEDIUM"),
    ("assure", "əˈʃʊr", "v. 保证；使确信", "verb", "MEDIUM"),
    ("atmosphere", "ˈætməsfɪr", "n. 大气；氛围", "noun", "MEDIUM"),
    ("attach", "əˈtætʃ", "v. 附上；系上", "verb", "MEDIUM"),
    ("attempt", "əˈtempt", "v. 尝试 n. 企图", "verb", "MEDIUM"),
    ("attitude", "ˈætɪtuːd", "n. 态度；看法", "noun", "EASY"),
    ("attract", "əˈtrækt", "v. 吸引", "verb", "EASY"),
    ("audience", "ˈɔːdiəns", "n. 观众；听众", "noun", "EASY"),
    ("authority", "əˈθɔːrəti", "n. 权威；当局", "noun", "MEDIUM"),
    ("available", "əˈveɪləbl", "adj. 可获得的；有空的", "adj", "EASY"),
    ("average", "ˈævərɪdʒ", "n. 平均 adj. 平均的", "noun", "EASY"),
    ("avoid", "əˈvɔɪd", "v. 避免；回避", "verb", "EASY"),
    ("aware", "əˈwer", "adj. 意识到的；知道的", "adj", "MEDIUM"),
    ("awful", "ˈɔːfl", "adj. 糟糕的；可怕的", "adj", "EASY"),

    # ===== B =====
    ("background", "ˈbækɡraʊnd", "n. 背景；经历", "noun", "EASY"),
    ("balance", "ˈbæləns", "n. 平衡 v. 使平衡", "noun", "MEDIUM"),
    ("ban", "bæn", "v. 禁止 n. 禁令", "verb", "MEDIUM"),
    ("barrier", "ˈbæriər", "n. 障碍；屏障", "noun", "MEDIUM"),
    ("basis", "ˈbeɪsɪs", "n. 基础；根据", "noun", "MEDIUM"),
    ("battle", "ˈbætl", "n. 战斗；斗争", "noun", "MEDIUM"),
    ("behave", "bɪˈheɪv", "v. 表现；举止", "verb", "MEDIUM"),
    ("belief", "bɪˈliːf", "n. 信念；信仰", "noun", "MEDIUM"),
    ("belong", "bɪˈlɔːŋ", "v. 属于；应归于", "verb", "EASY"),
    ("beneath", "bɪˈniːθ", "prep. 在…下方", "prep", "MEDIUM"),
    ("benefit", "ˈbenɪfɪt", "n. 利益 v. 有益于", "noun", "EASY"),
    ("betray", "bɪˈtreɪ", "v. 背叛；出卖", "verb", "HARD"),
    ("beyond", "bɪˈjɑːnd", "prep. 超出；越过", "prep", "EASY"),
    ("blame", "bleɪm", "v. 责备 n. 责任", "verb", "EASY"),
    ("border", "ˈbɔːrdər", "n. 边界；边境", "noun", "MEDIUM"),
    ("bother", "ˈbɑːðər", "v. 打扰；烦扰", "verb", "EASY"),
    ("boundary", "ˈbaʊndri", "n. 边界；界限", "noun", "MEDIUM"),
    ("brief", "briːf", "adj. 简短的 n. 摘要", "adj", "EASY"),
    ("brilliant", "ˈbrɪliənt", "adj. 杰出的；灿烂的", "adj", "MEDIUM"),
    ("budget", "ˈbʌdʒɪt", "n. 预算 v. 编预算", "noun", "MEDIUM"),
    ("burden", "ˈbɜːrdn", "n. 负担 v. 使负重", "noun", "MEDIUM"),
    ("burst", "bɜːrst", "v. 爆裂；突发", "verb", "MEDIUM"),

    # ===== C =====
    ("calculate", "ˈkælkjuleɪt", "v. 计算；估算", "verb", "EASY"),
    ("campaign", "kæmˈpeɪn", "n. 运动；战役", "noun", "MEDIUM"),
    ("candidate", "ˈkændɪdət", "n. 候选人；应试者", "noun", "MEDIUM"),
    ("capable", "ˈkeɪpəbl", "adj. 有能力的；能干的", "adj", "MEDIUM"),
    ("capacity", "kəˈpæsəti", "n. 容量；能力", "noun", "MEDIUM"),
    ("capture", "ˈkæptʃər", "v. 捕获；夺取", "verb", "MEDIUM"),
    ("career", "kəˈrɪr", "n. 职业；生涯", "noun", "EASY"),
    ("cautious", "ˈkɔːʃəs", "adj. 谨慎的；小心的", "adj", "MEDIUM"),
    ("celebrate", "ˈselɪbreɪt", "v. 庆祝", "verb", "EASY"),
    ("ceremony", "ˈserəmoʊni", "n. 典礼；仪式", "noun", "MEDIUM"),
    ("challenge", "ˈtʃælɪndʒ", "n. 挑战 v. 向…挑战", "noun", "EASY"),
    ("character", "ˈkærəktər", "n. 性格；角色；字符", "noun", "EASY"),
    ("characteristic", "ˌkærəktəˈrɪstɪk", "n. 特征 adj. 典型的", "noun", "MEDIUM"),
    ("charge", "tʃɑːrdʒ", "v. 收费；充电 n. 费用", "verb", "EASY"),
    ("cheerful", "ˈtʃɪrfl", "adj. 快乐的；开朗的", "adj", "EASY"),
    ("circumstance", "ˈsɜːrkəmstæns", "n. 环境；情况", "noun", "MEDIUM"),
    ("civil", "ˈsɪvl", "adj. 公民的；文明的", "adj", "MEDIUM"),
    ("claim", "kleɪm", "v. 声称 n. 主张；索赔", "verb", "MEDIUM"),
    ("classify", "ˈklæsɪfaɪ", "v. 分类", "verb", "MEDIUM"),
    ("climate", "ˈklaɪmət", "n. 气候；风气", "noun", "EASY"),
    ("coincidence", "koʊˈɪnsɪdəns", "n. 巧合", "noun", "HARD"),
    ("collapse", "kəˈlæps", "v. 倒塌；崩溃", "verb", "MEDIUM"),
    ("colleague", "ˈkɑːliːɡ", "n. 同事", "noun", "MEDIUM"),
    ("combine", "kəmˈbaɪn", "v. 结合；联合", "verb", "MEDIUM"),
    ("comfort", "ˈkʌmfərt", "n. 舒适 v. 安慰", "noun", "EASY"),
    ("command", "kəˈmænd", "v. 命令 n. 命令", "verb", "MEDIUM"),
    ("comment", "ˈkɑːment", "n. 评论 v. 评论", "noun", "EASY"),
    ("commercial", "kəˈmɜːrʃl", "adj. 商业的 n. 广告", "adj", "MEDIUM"),
    ("commit", "kəˈmɪt", "v. 犯（罪）；承诺", "verb", "MEDIUM"),
    ("communicate", "kəˈmjuːnɪkeɪt", "v. 交流；传达", "verb", "EASY"),
    ("community", "kəˈmjuːnəti", "n. 社区；群体", "noun", "EASY"),
    ("compare", "kəmˈper", "v. 比较", "verb", "EASY"),
    ("compete", "kəmˈpiːt", "v. 竞争；比赛", "verb", "MEDIUM"),
    ("complain", "kəmˈpleɪn", "v. 抱怨；投诉", "verb", "EASY"),
    ("complex", "ˈkɑːmpleks", "adj. 复杂的 n. 综合体", "adj", "MEDIUM"),
    ("complicate", "ˈkɑːmplɪkeɪt", "v. 使复杂化", "verb", "HARD"),
    ("compose", "kəmˈpoʊz", "v. 组成；创作", "verb", "MEDIUM"),
    ("comprehensive", "ˌkɑːmprɪˈhensɪv", "adj. 全面的；综合的", "adj", "HARD"),
    ("concentrate", "ˈkɑːnsntreɪt", "v. 集中；专心", "verb", "MEDIUM"),
    ("concept", "ˈkɑːnsept", "n. 概念；观念", "noun", "MEDIUM"),
    ("concern", "kənˈsɜːrn", "v. 涉及 n. 担心；关注", "verb", "MEDIUM"),
    ("conclude", "kənˈkluːd", "v. 得出结论；结束", "verb", "MEDIUM"),
    ("condition", "kənˈdɪʃn", "n. 条件；状况", "noun", "EASY"),
    ("conduct", "kənˈdʌkt", "v. 进行；指挥 n. 行为", "verb", "MEDIUM"),
    ("conference", "ˈkɑːnfərəns", "n. 会议；讨论会", "noun", "MEDIUM"),
    ("confidence", "ˈkɑːnfɪdəns", "n. 信心；信任", "noun", "MEDIUM"),
    ("confirm", "kənˈfɜːrm", "v. 确认；证实", "verb", "MEDIUM"),
    ("conflict", "ˈkɑːnflɪkt", "n. 冲突；矛盾", "noun", "MEDIUM"),
    ("confuse", "kənˈfjuːz", "v. 使困惑；混淆", "verb", "MEDIUM"),
    ("connect", "kəˈnekt", "v. 连接；联系", "verb", "EASY"),
    ("conscious", "ˈkɑːnʃəs", "adj. 有意识的；清醒的", "adj", "MEDIUM"),
    ("consequence", "ˈkɑːnsɪkwens", "n. 后果；结果", "noun", "MEDIUM"),
    ("conservative", "kənˈsɜːrvətɪv", "adj. 保守的", "adj", "HARD"),
    ("consider", "kənˈsɪdər", "v. 考虑；认为", "verb", "EASY"),
    ("consist", "kənˈsɪst", "v. 组成；在于", "verb", "MEDIUM"),
    ("constant", "ˈkɑːnstənt", "adj. 持续的；不变的", "adj", "MEDIUM"),
    ("construct", "kənˈstrʌkt", "v. 建造；构建", "verb", "MEDIUM"),
    ("consult", "kənˈsʌlt", "v. 咨询；查阅", "verb", "MEDIUM"),
    ("consume", "kənˈsuːm", "v. 消费；消耗", "verb", "MEDIUM"),
    ("contain", "kənˈteɪn", "v. 包含；容纳", "verb", "MEDIUM"),
    ("contemporary", "kənˈtempəreri", "adj. 当代的；同时代的", "adj", "HARD"),
    ("content", "ˈkɑːntent", "n. 内容；含量 adj. 满足的", "noun", "MEDIUM"),
    ("context", "ˈkɑːntekst", "n. 上下文；背景", "noun", "MEDIUM"),
    ("contract", "ˈkɑːntrækt", "n. 合同 v. 收缩", "noun", "MEDIUM"),
    ("contrast", "ˈkɑːntræst", "n. 对比 v. 对比", "noun", "MEDIUM"),
    ("contribute", "kənˈtrɪbjuːt", "v. 贡献；促成", "verb", "MEDIUM"),
    ("controversial", "ˌkɑːntrəˈvɜːrʃl", "adj. 有争议的", "adj", "HARD"),
    ("convenient", "kənˈviːniənt", "adj. 方便的", "adj", "EASY"),
    ("conventional", "kənˈvenʃənl", "adj. 传统的；常规的", "adj", "HARD"),
    ("convince", "kənˈvɪns", "v. 使信服；说服", "verb", "MEDIUM"),
    ("cooperate", "koʊˈɑːpəreɪt", "v. 合作；协作", "verb", "MEDIUM"),
    ("cope", "koʊp", "v. 应对；处理", "verb", "MEDIUM"),
    ("corporation", "ˌkɔːrpəˈreɪʃn", "n. 公司；法人", "noun", "MEDIUM"),
    ("correspond", "ˌkɔːrəˈspɑːnd", "v. 相符；通信", "verb", "HARD"),
    ("courage", "ˈkɜːrɪdʒ", "n. 勇气；胆量", "noun", "EASY"),
    ("crucial", "ˈkruːʃl", "adj. 至关重要的", "adj", "MEDIUM"),
    ("cultivate", "ˈkʌltɪveɪt", "v. 培养；耕作", "verb", "MEDIUM"),
    ("curious", "ˈkjʊriəs", "adj. 好奇的", "adj", "EASY"),
    ("current", "ˈkɜːrənt", "adj. 当前的 n. 水流；电流", "adj", "EASY"),

    # ===== D =====
    ("declare", "dɪˈkler", "v. 宣布；声明", "verb", "MEDIUM"),
    ("decline", "dɪˈklaɪn", "v. 下降；拒绝", "verb", "MEDIUM"),
    ("decorate", "ˈdekəreɪt", "v. 装饰", "verb", "MEDIUM"),
    ("decrease", "dɪˈkriːs", "v. 减少 n. 减少", "verb", "MEDIUM"),
    ("dedicate", "ˈdedɪkeɪt", "v. 奉献；献身", "verb", "HARD"),
    ("defeat", "dɪˈfiːt", "v. 打败 n. 失败", "verb", "MEDIUM"),
    ("defend", "dɪˈfend", "v. 保卫；辩护", "verb", "MEDIUM"),
    ("define", "dɪˈfaɪn", "v. 定义；阐明", "verb", "MEDIUM"),
    ("definite", "ˈdefɪnət", "adj. 明确的；肯定的", "adj", "MEDIUM"),
    ("degree", "dɪˈɡriː", "n. 程度；学位", "noun", "EASY"),
    ("delay", "dɪˈleɪ", "v. 推迟 n. 耽搁", "verb", "EASY"),
    ("delight", "dɪˈlaɪt", "n. 高兴 v. 使高兴", "noun", "EASY"),
    ("deliver", "dɪˈlɪvər", "v. 递送；发表", "verb", "EASY"),
    ("demand", "dɪˈmænd", "v. 要求 n. 需求", "verb", "EASY"),
    ("demonstrate", "ˈdemənstreɪt", "v. 证明；演示", "verb", "MEDIUM"),
    ("deny", "dɪˈnaɪ", "v. 否认；拒绝", "verb", "MEDIUM"),
    ("depend", "dɪˈpend", "v. 依赖；取决于", "verb", "EASY"),
    ("deposit", "dɪˈpɑːzɪt", "v. 存放 n. 存款；押金", "verb", "MEDIUM"),
    ("depress", "dɪˈpres", "v. 使沮丧；使萧条", "verb", "MEDIUM"),
    ("derive", "dɪˈraɪv", "v. 获得；起源", "verb", "HARD"),
    ("describe", "dɪˈskraɪb", "v. 描述", "verb", "EASY"),
    ("deserve", "dɪˈzɜːrv", "v. 应得；值得", "verb", "MEDIUM"),
    ("design", "dɪˈzaɪn", "v. 设计 n. 设计", "verb", "EASY"),
    ("desire", "dɪˈzaɪər", "n. 渴望 v. 渴望", "noun", "MEDIUM"),
    ("despite", "dɪˈspaɪt", "prep. 尽管", "prep", "MEDIUM"),
    ("destination", "ˌdestɪˈneɪʃn", "n. 目的地", "noun", "MEDIUM"),
    ("destroy", "dɪˈstrɔɪ", "v. 破坏；摧毁", "verb", "MEDIUM"),
    ("determine", "dɪˈtɜːrmɪn", "v. 决定；决心", "verb", "MEDIUM"),
    ("develop", "dɪˈveləp", "v. 发展；开发", "verb", "EASY"),
    ("device", "dɪˈvaɪs", "n. 设备；装置", "noun", "MEDIUM"),
    ("devote", "dɪˈvoʊt", "v. 奉献；投入", "verb", "MEDIUM"),
    ("diet", "ˈdaɪət", "n. 饮食；节食", "noun", "EASY"),
    ("differ", "ˈdɪfər", "v. 不同；相异", "verb", "MEDIUM"),
    ("digest", "daɪˈdʒest", "v. 消化；领会", "verb", "MEDIUM"),
    ("digital", "ˈdɪdʒɪtl", "adj. 数字的", "adj", "EASY"),
    ("dignity", "ˈdɪɡnəti", "n. 尊严；庄重", "noun", "HARD"),
    ("dimension", "daɪˈmenʃn", "n. 尺寸；维度", "noun", "HARD"),
    ("direct", "dəˈrekt", "adj. 直接的 v. 指导", "adj", "EASY"),
    ("disaster", "dɪˈzæstər", "n. 灾难", "noun", "MEDIUM"),
    ("discipline", "ˈdɪsəplɪn", "n. 纪律；学科", "noun", "MEDIUM"),
    ("discount", "ˈdɪskaʊnt", "n. 折扣 v. 打折", "noun", "EASY"),
    ("discover", "dɪˈskʌvər", "v. 发现", "verb", "EASY"),
    ("discuss", "dɪˈskʌs", "v. 讨论", "verb", "EASY"),
    ("dismiss", "dɪsˈmɪs", "v. 解雇；驳回", "verb", "MEDIUM"),
    ("display", "dɪˈspleɪ", "v. 展示 n. 展示", "verb", "MEDIUM"),
    ("distinguish", "dɪˈstɪŋɡwɪʃ", "v. 区分；辨别", "verb", "MEDIUM"),
    ("distribute", "dɪˈstrɪbjuːt", "v. 分配；分发", "verb", "MEDIUM"),
    ("disturb", "dɪˈstɜːrb", "v. 打扰；扰乱", "verb", "MEDIUM"),
    ("diverse", "daɪˈvɜːrs", "adj. 多样的；不同的", "adj", "MEDIUM"),
    ("document", "ˈdɑːkjumənt", "n. 文件；文档", "noun", "MEDIUM"),
    ("domestic", "dəˈmestɪk", "adj. 国内的；家庭的", "adj", "MEDIUM"),
    ("dominate", "ˈdɑːmɪneɪt", "v. 支配；主导", "verb", "MEDIUM"),
    ("donate", "ˈdoʊneɪt", "v. 捐赠", "verb", "MEDIUM"),
    ("doubt", "daʊt", "n. 怀疑 v. 怀疑", "noun", "EASY"),
    ("dramatic", "drəˈmætɪk", "adj. 戏剧性的；巨大的", "adj", "MEDIUM"),
    ("drawback", "ˈdrɔːbæk", "n. 缺点；不利条件", "noun", "MEDIUM"),
    ("duration", "duˈreɪʃn", "n. 持续时间", "noun", "MEDIUM"),
    ("dynamic", "daɪˈnæmɪk", "adj. 动态的；有活力的", "adj", "MEDIUM"),

    # ===== E =====
    ("eager", "ˈiːɡər", "adj. 渴望的；热切的", "adj", "MEDIUM"),
    ("earn", "ɜːrn", "v. 赚得；赢得", "verb", "EASY"),
    ("economy", "ɪˈkɑːnəmi", "n. 经济；节约", "noun", "MEDIUM"),
    ("edge", "edʒ", "n. 边缘；优势", "noun", "EASY"),
    ("edit", "ˈedɪt", "v. 编辑", "verb", "MEDIUM"),
    ("educate", "ˈedʒukeɪt", "v. 教育", "verb", "MEDIUM"),
    ("effective", "ɪˈfektɪv", "adj. 有效的", "adj", "MEDIUM"),
    ("efficient", "ɪˈfɪʃnt", "adj. 高效的", "adj", "MEDIUM"),
    ("effort", "ˈefərt", "n. 努力；成就", "noun", "EASY"),
    ("elaborate", "ɪˈlæbərət", "adj. 精心制作的 v. 详述", "adj", "HARD"),
    ("elect", "ɪˈlekt", "v. 选举", "verb", "MEDIUM"),
    ("eliminate", "ɪˈlɪmɪneɪt", "v. 消除；淘汰", "verb", "MEDIUM"),
    ("embarrass", "ɪmˈbærəs", "v. 使尴尬", "verb", "MEDIUM"),
    ("emerge", "iˈmɜːrdʒ", "v. 出现；浮现", "verb", "MEDIUM"),
    ("emotion", "ɪˈmoʊʃn", "n. 情感；情绪", "noun", "MEDIUM"),
    ("emphasize", "ˈemfəsaɪz", "v. 强调", "verb", "MEDIUM"),
    ("employ", "ɪmˈplɔɪ", "v. 雇用；使用", "verb", "MEDIUM"),
    ("encounter", "ɪnˈkaʊntər", "v. 遇到 n. 遭遇", "verb", "MEDIUM"),
    ("encourage", "ɪnˈkɜːrɪdʒ", "v. 鼓励", "verb", "EASY"),
    ("energy", "ˈenərdʒi", "n. 能量；精力", "noun", "EASY"),
    ("engage", "ɪnˈɡeɪdʒ", "v. 从事；吸引；订婚", "verb", "MEDIUM"),
    ("enhance", "ɪnˈhæns", "v. 增强；提高", "verb", "MEDIUM"),
    ("enormous", "ɪˈnɔːrməs", "adj. 巨大的", "adj", "MEDIUM"),
    ("ensure", "ɪnˈʃʊr", "v. 确保；保证", "verb", "MEDIUM"),
    ("enthusiasm", "ɪnˈθuːziæzəm", "n. 热情；热忱", "noun", "MEDIUM"),
    ("entire", "ɪnˈtaɪər", "adj. 全部的；整个的", "adj", "EASY"),
    ("entitle", "ɪnˈtaɪtl", "v. 使有权利；命名", "verb", "MEDIUM"),
    ("environment", "ɪnˈvaɪrənmənt", "n. 环境", "noun", "EASY"),
    ("equipment", "ɪˈkwɪpmənt", "n. 设备；装备", "noun", "EASY"),
    ("equivalent", "ɪˈkwɪvələnt", "adj. 等价的 n. 等价物", "adj", "HARD"),
    ("escape", "ɪˈskeɪp", "v. 逃跑；逃避", "verb", "EASY"),
    ("essential", "ɪˈsenʃl", "adj. 必要的；本质的", "adj", "MEDIUM"),
    ("establish", "ɪˈstæblɪʃ", "v. 建立；确立", "verb", "MEDIUM"),
    ("estimate", "ˈestɪmeɪt", "v. 估计 n. 估计", "verb", "MEDIUM"),
    ("evaluate", "ɪˈvæljueɪt", "v. 评估；评价", "verb", "MEDIUM"),
    ("eventually", "ɪˈventʃuəli", "adv. 最终；终于", "adverb", "MEDIUM"),
    ("evidence", "ˈevɪdəns", "n. 证据", "noun", "MEDIUM"),
    ("evident", "ˈevɪdənt", "adj. 明显的", "adj", "MEDIUM"),
    ("examine", "ɪɡˈzæmɪn", "v. 检查；考查", "verb", "MEDIUM"),
    ("exceed", "ɪkˈsiːd", "v. 超过；超出", "verb", "MEDIUM"),
    ("excellent", "ˈeksələnt", "adj. 极好的；优秀的", "adj", "EASY"),
    ("exchange", "ɪksˈtʃeɪndʒ", "v. 交换 n. 交换", "verb", "MEDIUM"),
    ("exclude", "ɪkˈskluːd", "v. 排除；不包括", "verb", "MEDIUM"),
    ("exhaust", "ɪɡˈzɔːst", "v. 使筋疲力尽；耗尽", "verb", "MEDIUM"),
    ("exist", "ɪɡˈzɪst", "v. 存在；生存", "verb", "EASY"),
    ("expand", "ɪkˈspænd", "v. 扩大；膨胀", "verb", "MEDIUM"),
    ("expect", "ɪkˈspekt", "v. 期望；预料", "verb", "EASY"),
    ("expense", "ɪkˈspens", "n. 花费；费用", "noun", "MEDIUM"),
    ("experience", "ɪkˈspɪriəns", "n. 经验；经历", "noun", "EASY"),
    ("experiment", "ɪkˈsperɪmənt", "n. 实验 v. 实验", "noun", "EASY"),
    ("expert", "ˈekspɜːrt", "n. 专家 adj. 熟练的", "noun", "EASY"),
    ("explain", "ɪkˈspleɪn", "v. 解释", "verb", "EASY"),
    ("explore", "ɪkˈsplɔːr", "v. 探索；探究", "verb", "MEDIUM"),
    ("expose", "ɪkˈspoʊz", "v. 暴露；揭露", "verb", "MEDIUM"),
    ("express", "ɪkˈspres", "v. 表达 adj. 特快的", "verb", "EASY"),
    ("extend", "ɪkˈstend", "v. 延伸；扩大", "verb", "MEDIUM"),
    ("extent", "ɪkˈstent", "n. 程度；范围", "noun", "MEDIUM"),
    ("external", "ɪkˈstɜːrnl", "adj. 外部的；外界的", "adj", "MEDIUM"),
    ("extraordinary", "ɪkˈstrɔːrdəneri", "adj. 非凡的；特别的", "adj", "HARD"),

    # ===== F =====
    ("facility", "fəˈsɪləti", "n. 设施；便利", "noun", "MEDIUM"),
    ("factor", "ˈfæktər", "n. 因素；要素", "noun", "MEDIUM"),
    ("faculty", "ˈfæklti", "n. 才能；全体教员", "noun", "HARD"),
    ("familiar", "fəˈmɪliər", "adj. 熟悉的", "adj", "EASY"),
    ("fascinate", "ˈfæsɪneɪt", "v. 使着迷", "verb", "MEDIUM"),
    ("fashion", "ˈfæʃn", "n. 时尚；方式", "noun", "EASY"),
    ("fatal", "ˈfeɪtl", "adj. 致命的", "adj", "MEDIUM"),
    ("feature", "ˈfiːtʃər", "n. 特征；特色", "noun", "MEDIUM"),
    ("federal", "ˈfedərəl", "adj. 联邦的", "adj", "MEDIUM"),
    ("feedback", "ˈfiːdbæk", "n. 反馈", "noun", "MEDIUM"),
    ("fertile", "ˈfɜːrtl", "adj. 肥沃的；多产的", "adj", "MEDIUM"),
    ("finance", "ˈfaɪnæns", "n. 财政；金融", "noun", "MEDIUM"),
    ("flexible", "ˈfleksəbl", "adj. 灵活的；柔韧的", "adj", "MEDIUM"),
    ("flourish", "ˈflɜːrɪʃ", "v. 繁荣；茂盛", "verb", "MEDIUM"),
    ("fluent", "ˈfluːənt", "adj. 流利的", "adj", "MEDIUM"),
    ("focus", "ˈfoʊkəs", "v. 集中 n. 焦点", "verb", "EASY"),
    ("forbid", "fərˈbɪd", "v. 禁止", "verb", "MEDIUM"),
    ("forecast", "ˈfɔːrkæst", "v. 预测 n. 预测", "verb", "MEDIUM"),
    ("formal", "ˈfɔːrml", "adj. 正式的", "adj", "MEDIUM"),
    ("former", "ˈfɔːrmər", "adj. 以前的；前者的", "adj", "MEDIUM"),
    ("fortune", "ˈfɔːrtʃən", "n. 财富；运气", "noun", "MEDIUM"),
    ("foundation", "faʊnˈdeɪʃn", "n. 基础；基金会", "noun", "MEDIUM"),
    ("frequent", "ˈfriːkwənt", "adj. 频繁的", "adj", "MEDIUM"),
    ("frustrate", "ˈfrʌstreɪt", "v. 使沮丧；挫败", "verb", "MEDIUM"),
    ("fulfill", "fʊlˈfɪl", "v. 履行；实现", "verb", "MEDIUM"),
    ("function", "ˈfʌŋkʃn", "n. 功能 v. 运转", "noun", "EASY"),
    ("fundamental", "ˌfʌndəˈmentl", "adj. 基本的；根本的", "adj", "MEDIUM"),
    ("furnish", "ˈfɜːrnɪʃ", "v. 布置；提供", "verb", "HARD"),

    # ===== G =====
    ("gain", "ɡeɪn", "v. 获得；增加 n. 收益", "verb", "EASY"),
    ("gap", "ɡæp", "n. 差距；缺口", "noun", "EASY"),
    ("generate", "ˈdʒenəreɪt", "v. 产生；引起", "verb", "MEDIUM"),
    ("generous", "ˈdʒenərəs", "adj. 慷慨的；大方的", "adj", "MEDIUM"),
    ("genuine", "ˈdʒenjuɪn", "adj. 真正的；真诚的", "adj", "MEDIUM"),
    ("gesture", "ˈdʒestʃər", "n. 手势；姿态", "noun", "MEDIUM"),
    ("global", "ˈɡloʊbl", "adj. 全球的", "adj", "MEDIUM"),
    ("gradual", "ˈɡrædʒuəl", "adj. 逐渐的", "adj", "MEDIUM"),
    ("grant", "ɡrænt", "v. 授予 n. 拨款", "verb", "MEDIUM"),
    ("grateful", "ˈɡreɪtfl", "adj. 感激的", "adj", "MEDIUM"),
    ("guarantee", "ˌɡærənˈtiː", "v. 保证 n. 保证", "verb", "MEDIUM"),
    ("guideline", "ˈɡaɪdlaɪn", "n. 指导方针；准则", "noun", "MEDIUM"),
    ("guilty", "ˈɡɪlti", "adj. 有罪的；内疚的", "adj", "MEDIUM"),

    # ===== H =====
    ("habit", "ˈhæbɪt", "n. 习惯", "noun", "EASY"),
    ("handle", "ˈhændl", "v. 处理 n. 把手", "verb", "EASY"),
    ("harmony", "ˈhɑːrməni", "n. 和谐；融洽", "noun", "MEDIUM"),
    ("hesitate", "ˈhezɪteɪt", "v. 犹豫；迟疑", "verb", "MEDIUM"),
    ("highlight", "ˈhaɪlaɪt", "v. 强调 n. 亮点", "verb", "MEDIUM"),
    ("horizon", "həˈraɪzn", "n. 地平线；眼界", "noun", "MEDIUM"),
    ("hostile", "ˈhɑːstl", "adj. 敌对的", "adj", "MEDIUM"),
    ("humble", "ˈhʌmbl", "adj. 谦逊的；卑微的", "adj", "MEDIUM"),
    ("hypothesis", "haɪˈpɑːθəsɪs", "n. 假设；假说", "noun", "HARD"),

    # ===== I =====
    ("identical", "aɪˈdentɪkl", "adj. 完全相同的", "adj", "MEDIUM"),
    ("identify", "aɪˈdentɪfaɪ", "v. 识别；确认", "verb", "MEDIUM"),
    ("ignore", "ɪɡˈnɔːr", "v. 忽视；不理会", "verb", "EASY"),
    ("illustrate", "ˈɪləstreɪt", "v. 说明；举例说明", "verb", "MEDIUM"),
    ("imagine", "ɪˈmædʒɪn", "v. 想象；设想", "verb", "EASY"),
    ("immediate", "ɪˈmiːdiət", "adj. 立即的；直接的", "adj", "MEDIUM"),
    ("impact", "ˈɪmpækt", "n. 影响；冲击", "noun", "MEDIUM"),
    ("implement", "ˈɪmplɪment", "v. 实施；执行", "verb", "MEDIUM"),
    ("imply", "ɪmˈplaɪ", "v. 暗示；意味着", "verb", "MEDIUM"),
    ("import", "ˈɪmpɔːrt", "v. 进口 n. 进口", "verb", "MEDIUM"),
    ("impose", "ɪmˈpoʊz", "v. 强加；征收", "verb", "MEDIUM"),
    ("impress", "ɪmˈpres", "v. 给…留下印象", "verb", "MEDIUM"),
    ("improve", "ɪmˈpruːv", "v. 改进；提高", "verb", "EASY"),
    ("incident", "ˈɪnsɪdənt", "n. 事件；事故", "noun", "MEDIUM"),
    ("include", "ɪnˈkluːd", "v. 包括；包含", "verb", "EASY"),
    ("income", "ˈɪnkʌm", "n. 收入", "noun", "EASY"),
    ("increase", "ɪnˈkriːs", "v. 增加 n. 增加", "verb", "EASY"),
    ("indicate", "ˈɪndɪkeɪt", "v. 表明；指示", "verb", "MEDIUM"),
    ("individual", "ˌɪndɪˈvɪdʒuəl", "adj. 个人的 n. 个人", "adj", "MEDIUM"),
    ("industry", "ˈɪndəstri", "n. 工业；行业", "noun", "EASY"),
    ("inevitable", "ɪnˈevɪtəbl", "adj. 不可避免的", "adj", "HARD"),
    ("infer", "ɪnˈfɜːr", "v. 推断", "verb", "HARD"),
    ("influence", "ˈɪnfluəns", "n. 影响 v. 影响", "noun", "MEDIUM"),
    ("inform", "ɪnˈfɔːrm", "v. 通知；告知", "verb", "MEDIUM"),
    ("initial", "ɪˈnɪʃl", "adj. 最初的 n. 首字母", "adj", "MEDIUM"),
    ("initiative", "ɪˈnɪʃətɪv", "n. 主动性；倡议", "noun", "HARD"),
    ("innovate", "ˈɪnəveɪt", "v. 创新；革新", "verb", "MEDIUM"),
    ("inquire", "ɪnˈkwaɪər", "v. 询问；调查", "verb", "MEDIUM"),
    ("insight", "ˈɪnsaɪt", "n. 洞察力；深刻见解", "noun", "HARD"),
    ("insist", "ɪnˈsɪst", "v. 坚持；坚决要求", "verb", "MEDIUM"),
    ("inspect", "ɪnˈspekt", "v. 检查；视察", "verb", "MEDIUM"),
    ("inspire", "ɪnˈspaɪər", "v. 激励；启发", "verb", "MEDIUM"),
    ("install", "ɪnˈstɔːl", "v. 安装", "verb", "MEDIUM"),
    ("instance", "ˈɪnstəns", "n. 实例；情况", "noun", "MEDIUM"),
    ("instant", "ˈɪnstənt", "adj. 立即的 n. 瞬间", "adj", "MEDIUM"),
    ("institute", "ˈɪnstɪtuːt", "n. 学院；机构", "noun", "MEDIUM"),
    ("instruct", "ɪnˈstrʌkt", "v. 指导；指示", "verb", "MEDIUM"),
    ("insult", "ɪnˈsʌlt", "v. 侮辱 n. 侮辱", "verb", "MEDIUM"),
    ("integrate", "ˈɪntɪɡreɪt", "v. 整合；融合", "verb", "MEDIUM"),
    ("intelligent", "ɪnˈtelɪdʒənt", "adj. 聪明的；智能的", "adj", "MEDIUM"),
    ("intend", "ɪnˈtend", "v. 打算；意欲", "verb", "MEDIUM"),
    ("intense", "ɪnˈtens", "adj. 强烈的；紧张的", "adj", "MEDIUM"),
    ("interact", "ˌɪntərˈækt", "v. 互动；相互作用", "verb", "MEDIUM"),
    ("interest", "ˈɪntrəst", "n. 兴趣；利息", "noun", "EASY"),
    ("interpret", "ɪnˈtɜːrprɪt", "v. 解释；口译", "verb", "MEDIUM"),
    ("interrupt", "ˌɪntəˈrʌpt", "v. 打断；中断", "verb", "MEDIUM"),
    ("interval", "ˈɪntərvl", "n. 间隔；间歇", "noun", "MEDIUM"),
    ("investigate", "ɪnˈvestɪɡeɪt", "v. 调查；研究", "verb", "MEDIUM"),
    ("involve", "ɪnˈvɑːlv", "v. 涉及；包含", "verb", "MEDIUM"),
    ("isolate", "ˈaɪsəleɪt", "v. 隔离；孤立", "verb", "MEDIUM"),
    ("issue", "ˈɪʃuː", "n. 问题；发行 v. 发布", "noun", "MEDIUM"),

    # ===== J =====
    ("journal", "ˈdʒɜːrnl", "n. 期刊；日志", "noun", "MEDIUM"),
    ("judge", "dʒʌdʒ", "v. 判断 n. 法官", "verb", "EASY"),
    ("justify", "ˈdʒʌstɪfaɪ", "v. 证明…合理", "verb", "MEDIUM"),

    # ===== K =====
    ("keen", "kiːn", "adj. 热衷的；敏锐的", "adj", "MEDIUM"),
    ("knowledge", "ˈnɑːlɪdʒ", "n. 知识", "noun", "EASY"),

    # ===== L =====
    ("label", "ˈleɪbl", "n. 标签 v. 贴标签", "noun", "MEDIUM"),
    ("labor", "ˈleɪbər", "n. 劳动；劳工", "noun", "MEDIUM"),
    ("lack", "læk", "n. 缺乏 v. 缺乏", "noun", "EASY"),
    ("landscape", "ˈlændskeɪp", "n. 风景；景观", "noun", "EASY"),
    ("launch", "lɔːntʃ", "v. 发射；发起", "verb", "MEDIUM"),
    ("leadership", "ˈliːdərʃɪp", "n. 领导力；领导", "noun", "MEDIUM"),
    ("legislation", "ˌledʒɪsˈleɪʃn", "n. 立法；法律", "noun", "HARD"),
    ("leisure", "ˈliːʒər", "n. 闲暇；空闲", "noun", "MEDIUM"),
    ("liberal", "ˈlɪbərəl", "adj. 开明的；自由的", "adj", "HARD"),
    ("license", "ˈlaɪsns", "n. 许可证 v. 许可", "noun", "MEDIUM"),
    ("likely", "ˈlaɪkli", "adj. 可能的 adv. 很可能", "adj", "EASY"),
    ("limit", "ˈlɪmɪt", "n. 限制 v. 限制", "noun", "EASY"),
    ("link", "lɪŋk", "v. 连接 n. 联系", "verb", "EASY"),
    ("locate", "ˈloʊkeɪt", "v. 定位；位于", "verb", "MEDIUM"),
    ("logic", "ˈlɑːdʒɪk", "n. 逻辑", "noun", "MEDIUM"),
    ("loyal", "ˈlɔɪəl", "adj. 忠诚的", "adj", "MEDIUM"),
    ("luxury", "ˈlʌkʃəri", "n. 奢侈；奢侈品", "noun", "MEDIUM"),

    # ===== M =====
    ("maintain", "meɪnˈteɪn", "v. 维持；保养", "verb", "MEDIUM"),
    ("major", "ˈmeɪdʒər", "adj. 主要的 n. 专业", "adj", "EASY"),
    ("manage", "ˈmænɪdʒ", "v. 管理；设法", "verb", "EASY"),
    ("manufacture", "ˌmænjuˈfæktʃər", "v. 制造 n. 制造", "verb", "MEDIUM"),
    ("margin", "ˈmɑːrdʒən", "n. 边缘；利润", "noun", "MEDIUM"),
    ("mature", "məˈtʃʊr", "adj. 成熟的 v. 成熟", "adj", "MEDIUM"),
    ("measure", "ˈmeʒər", "v. 测量 n. 措施", "verb", "EASY"),
    ("media", "ˈmiːdiə", "n. 媒体", "noun", "EASY"),
    ("mental", "ˈmentl", "adj. 精神的；智力的", "adj", "MEDIUM"),
    ("mention", "ˈmenʃn", "v. 提及 n. 提及", "verb", "EASY"),
    ("merit", "ˈmerɪt", "n. 优点；功绩", "noun", "MEDIUM"),
    ("method", "ˈmeθəd", "n. 方法", "noun", "EASY"),
    ("migrate", "ˈmaɪɡreɪt", "v. 迁移；移居", "verb", "MEDIUM"),
    ("mild", "maɪld", "adj. 温和的；轻微的", "adj", "MEDIUM"),
    ("minor", "ˈmaɪnər", "adj. 较小的；次要的", "adj", "MEDIUM"),
    ("moderate", "ˈmɑːdərət", "adj. 适度的；中等的", "adj", "MEDIUM"),
    ("modify", "ˈmɑːdɪfaɪ", "v. 修改；调整", "verb", "MEDIUM"),
    ("monitor", "ˈmɑːnɪtər", "v. 监控 n. 显示器", "verb", "MEDIUM"),
    ("motivate", "ˈmoʊtɪveɪt", "v. 激励；激发", "verb", "MEDIUM"),
    ("motive", "ˈmoʊtɪv", "n. 动机", "noun", "MEDIUM"),
    ("multiple", "ˈmʌltɪpl", "adj. 多重的；多个的", "adj", "MEDIUM"),
    ("mutual", "ˈmjuːtʃuəl", "adj. 相互的；共同的", "adj", "MEDIUM"),

    # ===== N =====
    ("negotiate", "nɪˈɡoʊʃieɪt", "v. 谈判；协商", "verb", "MEDIUM"),
    ("neutral", "ˈnuːtrəl", "adj. 中立的", "adj", "MEDIUM"),
    ("noticeable", "ˈnoʊtɪsəbl", "adj. 显而易见的", "adj", "MEDIUM"),
    ("notion", "ˈnoʊʃn", "n. 概念；想法", "noun", "MEDIUM"),
    ("nuclear", "ˈnuːkliər", "adj. 核的；核心的", "adj", "MEDIUM"),
    ("numerous", "ˈnuːmərəs", "adj. 众多的", "adj", "MEDIUM"),
    ("nurture", "ˈnɜːrtʃər", "v. 培养；养育", "verb", "HARD"),

    # ===== O =====
    ("obey", "əˈbeɪ", "v. 服从；遵守", "verb", "MEDIUM"),
    ("object", "ˈɑːbdʒekt", "n. 物体；目标 v. 反对", "noun", "MEDIUM"),
    ("objective", "əbˈdʒektɪv", "n. 目标 adj. 客观的", "noun", "MEDIUM"),
    ("obligation", "ˌɑːblɪˈɡeɪʃn", "n. 义务；责任", "noun", "MEDIUM"),
    ("observe", "əbˈzɜːrv", "v. 观察；遵守", "verb", "MEDIUM"),
    ("obstacle", "ˈɑːbstəkl", "n. 障碍", "noun", "MEDIUM"),
    ("obtain", "əbˈteɪn", "v. 获得", "verb", "MEDIUM"),
    ("obvious", "ˈɑːbviəs", "adj. 明显的", "adj", "EASY"),
    ("occasion", "əˈkeɪʒn", "n. 场合；时机", "noun", "MEDIUM"),
    ("occupy", "ˈɑːkjupaɪ", "v. 占用；占据", "verb", "MEDIUM"),
    ("occur", "əˈkɜːr", "v. 发生；出现", "verb", "MEDIUM"),
    ("odd", "ɑːd", "adj. 奇怪的；奇数的", "adj", "MEDIUM"),
    ("offend", "əˈfend", "v. 冒犯；得罪", "verb", "MEDIUM"),
    ("offer", "ˈɔːfər", "v. 提供 n. 提议", "verb", "EASY"),
    ("opponent", "əˈpoʊnənt", "n. 对手；反对者", "noun", "MEDIUM"),
    ("opportunity", "ˌɑːpərˈtuːnəti", "n. 机会", "noun", "EASY"),
    ("oppose", "əˈpoʊz", "v. 反对", "verb", "MEDIUM"),
    ("optimistic", "ˌɑːptɪˈmɪstɪk", "adj. 乐观的", "adj", "MEDIUM"),
    ("option", "ˈɑːpʃn", "n. 选择；选项", "noun", "EASY"),
    ("ordinary", "ˈɔːrdneri", "adj. 普通的", "adj", "EASY"),
    ("organize", "ˈɔːrɡənaɪz", "v. 组织", "verb", "MEDIUM"),
    ("origin", "ˈɔːrɪdʒɪn", "n. 起源；出身", "noun", "MEDIUM"),
    ("outcome", "ˈaʊtkʌm", "n. 结果；成果", "noun", "MEDIUM"),
    ("outline", "ˈaʊtlaɪn", "n. 大纲；轮廓", "noun", "MEDIUM"),
    ("output", "ˈaʊtpʊt", "n. 产量；输出", "noun", "MEDIUM"),
    ("overcome", "ˌoʊvərˈkʌm", "v. 克服；战胜", "verb", "MEDIUM"),
    ("overlook", "ˌoʊvərˈlʊk", "v. 忽视；俯瞰", "verb", "MEDIUM"),
    ("overseas", "ˌoʊvərˈsiːz", "adj. 海外的 adv. 在海外", "adj", "MEDIUM"),
    ("overwhelm", "ˌoʊvərˈwelm", "v. 压倒；使不知所措", "verb", "HARD"),

    # ===== P =====
    ("participate", "pɑːrˈtɪsɪpeɪt", "v. 参与；参加", "verb", "MEDIUM"),
    ("particular", "pərˈtɪkjələr", "adj. 特定的；特别的", "adj", "MEDIUM"),
    ("passion", "ˈpæʃn", "n. 激情；热情", "noun", "MEDIUM"),
    ("pattern", "ˈpætərn", "n. 模式；图案", "noun", "MEDIUM"),
    ("peculiar", "pɪˈkjuːliər", "adj. 奇怪的；特有的", "adj", "HARD"),
    ("perceive", "pərˈsiːv", "v. 感知；认为", "verb", "MEDIUM"),
    ("perform", "pərˈfɔːrm", "v. 表演；执行", "verb", "MEDIUM"),
    ("permanent", "ˈpɜːrmənənt", "adj. 永久的", "adj", "MEDIUM"),
    ("permit", "pərˈmɪt", "v. 允许 n. 许可证", "verb", "MEDIUM"),
    ("persist", "pərˈsɪst", "v. 坚持；持续", "verb", "MEDIUM"),
    ("perspective", "pərˈspektɪv", "n. 观点；视角", "noun", "MEDIUM"),
    ("persuade", "pərˈsweɪd", "v. 说服", "verb", "MEDIUM"),
    ("phenomenon", "fəˈnɑːmɪnən", "n. 现象", "noun", "HARD"),
    ("philosophy", "fəˈlɑːsəfi", "n. 哲学；理念", "noun", "HARD"),
    ("physical", "ˈfɪzɪkl", "adj. 身体的；物理的", "adj", "MEDIUM"),
    ("policy", "ˈpɑːləsi", "n. 政策；方针", "noun", "MEDIUM"),
    ("polish", "ˈpɑːlɪʃ", "v. 擦亮；润色", "verb", "MEDIUM"),
    ("portion", "ˈpɔːrʃn", "n. 部分；一份", "noun", "MEDIUM"),
    ("potential", "pəˈtenʃl", "adj. 潜在的 n. 潜力", "adj", "MEDIUM"),
    ("practical", "ˈpræktɪkl", "adj. 实际的；实用的", "adj", "EASY"),
    ("precise", "prɪˈsaɪs", "adj. 精确的", "adj", "MEDIUM"),
    ("predict", "prɪˈdɪkt", "v. 预测", "verb", "MEDIUM"),
    ("prefer", "prɪˈfɜːr", "v. 更喜欢", "verb", "EASY"),
    ("prejudice", "ˈpredʒudɪs", "n. 偏见", "noun", "MEDIUM"),
    ("preliminary", "prɪˈlɪmɪneri", "adj. 初步的", "adj", "HARD"),
    ("preserve", "prɪˈzɜːrv", "v. 保存；保护", "verb", "MEDIUM"),
    ("pressure", "ˈpreʃər", "n. 压力", "noun", "EASY"),
    ("previous", "ˈpriːviəs", "adj. 先前的", "adj", "MEDIUM"),
    ("principle", "ˈprɪnsəpl", "n. 原则；原理", "noun", "MEDIUM"),
    ("priority", "praɪˈɔːrəti", "n. 优先；优先权", "noun", "MEDIUM"),
    ("privilege", "ˈprɪvəlɪdʒ", "n. 特权", "noun", "MEDIUM"),
    ("procedure", "prəˈsiːdʒər", "n. 程序；步骤", "noun", "MEDIUM"),
    ("process", "ˈprɑːses", "n. 过程 v. 处理", "noun", "EASY"),
    ("produce", "prəˈduːs", "v. 生产；产生", "verb", "EASY"),
    ("profession", "prəˈfeʃn", "n. 职业；专业", "noun", "MEDIUM"),
    ("profit", "ˈprɑːfɪt", "n. 利润 v. 获利", "noun", "MEDIUM"),
    ("progress", "ˈprɑːɡres", "n. 进步 v. 进展", "noun", "EASY"),
    ("prohibit", "prəˈhɪbɪt", "v. 禁止", "verb", "MEDIUM"),
    ("project", "ˈprɑːdʒekt", "n. 项目 v. 投射", "noun", "EASY"),
    ("promote", "prəˈmoʊt", "v. 促进；晋升", "verb", "MEDIUM"),
    ("proper", "ˈprɑːpər", "adj. 适当的；正确的", "adj", "EASY"),
    ("propose", "prəˈpoʊz", "v. 提议；求婚", "verb", "MEDIUM"),
    ("prospect", "ˈprɑːspekt", "n. 前景；展望", "noun", "MEDIUM"),
    ("protect", "prəˈtekt", "v. 保护", "verb", "EASY"),
    ("prove", "pruːv", "v. 证明", "verb", "EASY"),
    ("provide", "prəˈvaɪd", "v. 提供", "verb", "EASY"),
    ("purchase", "ˈpɜːrtʃəs", "v. 购买 n. 购买", "verb", "MEDIUM"),
    ("pursue", "pərˈsuː", "v. 追求；从事", "verb", "MEDIUM"),

    # ===== Q =====
    ("qualify", "ˈkwɑːlɪfaɪ", "v. 使合格；取得资格", "verb", "MEDIUM"),
    ("quantity", "ˈkwɑːntəti", "n. 数量", "noun", "MEDIUM"),
    ("quit", "kwɪt", "v. 停止；辞职", "verb", "EASY"),
    ("quote", "kwoʊt", "v. 引用 n. 引文", "verb", "MEDIUM"),

    # ===== R =====
    ("random", "ˈrændəm", "adj. 随机的", "adj", "MEDIUM"),
    ("range", "reɪndʒ", "n. 范围 v. 排列", "noun", "EASY"),
    ("rank", "ræŋk", "n. 等级 v. 排名", "noun", "MEDIUM"),
    ("rare", "rer", "adj. 稀有的；罕见的", "adj", "MEDIUM"),
    ("rational", "ˈræʃnəl", "adj. 理性的；合理的", "adj", "HARD"),
    ("react", "riˈækt", "v. 反应；起反应", "verb", "MEDIUM"),
    ("realistic", "ˌriːəˈlɪstɪk", "adj. 现实的", "adj", "MEDIUM"),
    ("recall", "rɪˈkɔːl", "v. 回忆；召回", "verb", "MEDIUM"),
    ("receive", "rɪˈsiːv", "v. 收到；接待", "verb", "EASY"),
    ("recognize", "ˈrekəɡnaɪz", "v. 认出；承认", "verb", "MEDIUM"),
    ("recommend", "ˌrekəˈmend", "v. 推荐；建议", "verb", "MEDIUM"),
    ("recover", "rɪˈkʌvər", "v. 恢复；康复", "verb", "MEDIUM"),
    ("reduce", "rɪˈduːs", "v. 减少；降低", "verb", "EASY"),
    ("refer", "rɪˈfɜːr", "v. 参考；提及", "verb", "MEDIUM"),
    ("reflect", "rɪˈflekt", "v. 反映；反思", "verb", "MEDIUM"),
    ("reform", "rɪˈfɔːrm", "v. 改革 n. 改革", "verb", "MEDIUM"),
    ("refuse", "rɪˈfjuːz", "v. 拒绝", "verb", "EASY"),
    ("regard", "rɪˈɡɑːrd", "v. 认为 n. 尊重", "verb", "MEDIUM"),
    ("region", "ˈriːdʒən", "n. 地区；区域", "noun", "EASY"),
    ("regret", "rɪˈɡret", "v. 后悔 n. 遗憾", "verb", "MEDIUM"),
    ("regulate", "ˈreɡjuleɪt", "v. 管理；调节", "verb", "MEDIUM"),
    ("reject", "rɪˈdʒekt", "v. 拒绝；否决", "verb", "MEDIUM"),
    ("relate", "rɪˈleɪt", "v. 联系；讲述", "verb", "MEDIUM"),
    ("release", "rɪˈliːs", "v. 释放；发布", "verb", "MEDIUM"),
    ("relevant", "ˈreləvənt", "adj. 相关的", "adj", "MEDIUM"),
    ("reliable", "rɪˈlaɪəbl", "adj. 可靠的", "adj", "MEDIUM"),
    ("relieve", "rɪˈliːv", "v. 缓解；减轻", "verb", "MEDIUM"),
    ("reluctant", "rɪˈlʌktənt", "adj. 不情愿的", "adj", "MEDIUM"),
    ("remain", "rɪˈmeɪn", "v. 保持；剩余", "verb", "EASY"),
    ("remarkable", "rɪˈmɑːrkəbl", "adj. 非凡的；显著的", "adj", "MEDIUM"),
    ("remove", "rɪˈmuːv", "v. 移除；消除", "verb", "EASY"),
    ("replace", "rɪˈpleɪs", "v. 替代；更换", "verb", "MEDIUM"),
    ("represent", "ˌreprɪˈzent", "v. 代表；象征", "verb", "MEDIUM"),
    ("require", "rɪˈkwaɪər", "v. 需要；要求", "verb", "EASY"),
    ("rescue", "ˈreskjuː", "v. 营救 n. 营救", "verb", "MEDIUM"),
    ("research", "rɪˈsɜːrtʃ", "n. 研究 v. 研究", "noun", "EASY"),
    ("resent", "rɪˈzent", "v. 憎恨；怨恨", "verb", "HARD"),
    ("reserve", "rɪˈzɜːrv", "v. 保留；预订", "verb", "MEDIUM"),
    ("resign", "rɪˈzaɪn", "v. 辞职；放弃", "verb", "MEDIUM"),
    ("resist", "rɪˈzɪst", "v. 抵抗；抵制", "verb", "MEDIUM"),
    ("resolve", "rɪˈzɑːlv", "v. 解决；决心", "verb", "MEDIUM"),
    ("resource", "ˈriːsɔːrs", "n. 资源", "noun", "MEDIUM"),
    ("respond", "rɪˈspɑːnd", "v. 回应；反应", "verb", "MEDIUM"),
    ("responsible", "rɪˈspɑːnsəbl", "adj. 负责的；有责任的", "adj", "MEDIUM"),
    ("restore", "rɪˈstɔːr", "v. 恢复；修复", "verb", "MEDIUM"),
    ("restrict", "rɪˈstrɪkt", "v. 限制；约束", "verb", "MEDIUM"),
    ("retain", "rɪˈteɪn", "v. 保留；保持", "verb", "MEDIUM"),
    ("reveal", "rɪˈviːl", "v. 揭示；透露", "verb", "MEDIUM"),
    ("reward", "rɪˈwɔːrd", "n. 奖励 v. 奖赏", "noun", "MEDIUM"),
    ("rigid", "ˈrɪdʒɪd", "adj. 严格的；僵硬的", "adj", "HARD"),
    ("routine", "ruːˈtiːn", "n. 常规；例行公事", "noun", "MEDIUM"),
    ("rural", "ˈrʊrəl", "adj. 农村的", "adj", "MEDIUM"),

    # ===== S =====
    ("sacrifice", "ˈsækrɪfaɪs", "v. 牺牲 n. 牺牲", "verb", "MEDIUM"),
    ("satisfy", "ˈsætɪsfaɪ", "v. 满足；使满意", "verb", "MEDIUM"),
    ("scale", "skeɪl", "n. 规模；刻度；天平", "noun", "MEDIUM"),
    ("scarce", "skers", "adj. 稀缺的；不足的", "adj", "MEDIUM"),
    ("scheme", "skiːm", "n. 计划；方案", "noun", "MEDIUM"),
    ("scope", "skoʊp", "n. 范围；眼界", "noun", "MEDIUM"),
    ("secure", "səˈkjʊr", "adj. 安全的 v. 获得；保护", "adj", "MEDIUM"),
    ("seek", "siːk", "v. 寻找；追求", "verb", "EASY"),
    ("select", "sɪˈlekt", "v. 选择 adj. 精选的", "verb", "MEDIUM"),
    ("sensitive", "ˈsensətɪv", "adj. 敏感的", "adj", "MEDIUM"),
    ("separate", "ˈsepəreɪt", "v. 分开 adj. 单独的", "verb", "EASY"),
    ("series", "ˈsɪriːz", "n. 系列；连续", "noun", "MEDIUM"),
    ("settle", "ˈsetl", "v. 解决；定居", "verb", "MEDIUM"),
    ("severe", "sɪˈvɪr", "adj. 严重的；严厉的", "adj", "MEDIUM"),
    ("shift", "ʃɪft", "v. 转移 n. 转变", "verb", "MEDIUM"),
    ("significant", "sɪɡˈnɪfɪkənt", "adj. 重要的；显著的", "adj", "MEDIUM"),
    ("similar", "ˈsɪmələr", "adj. 相似的", "adj", "EASY"),
    ("sincere", "sɪnˈsɪr", "adj. 真诚的", "adj", "MEDIUM"),
    ("situation", "ˌsɪtʃuˈeɪʃn", "n. 情况；形势", "noun", "EASY"),
    ("skeptical", "ˈskeptɪkl", "adj. 怀疑的", "adj", "HARD"),
    ("slight", "slaɪt", "adj. 轻微的；细小的", "adj", "MEDIUM"),
    ("solution", "səˈluːʃn", "n. 解决方案；溶液", "noun", "EASY"),
    ("sophisticated", "səˈfɪstɪkeɪtɪd", "adj. 复杂的；精密的；老练的", "adj", "HARD"),
    ("specific", "spəˈsɪfɪk", "adj. 具体的；特定的", "adj", "MEDIUM"),
    ("spectacular", "spekˈtækjələr", "adj. 壮观的", "adj", "HARD"),
    ("stable", "ˈsteɪbl", "adj. 稳定的 n. 马厩", "adj", "MEDIUM"),
    ("standard", "ˈstændərd", "n. 标准 adj. 标准的", "noun", "EASY"),
    ("statistics", "stəˈtɪstɪks", "n. 统计；统计学", "noun", "MEDIUM"),
    ("status", "ˈsteɪtəs", "n. 地位；状态", "noun", "MEDIUM"),
    ("strategy", "ˈstrætədʒi", "n. 策略；战略", "noun", "MEDIUM"),
    ("strengthen", "ˈstreŋθn", "v. 加强；增强", "verb", "MEDIUM"),
    ("stress", "stres", "n. 压力 v. 强调", "noun", "EASY"),
    ("structure", "ˈstrʌktʃər", "n. 结构", "noun", "MEDIUM"),
    ("struggle", "ˈstrʌɡl", "v. 奋斗 n. 挣扎", "verb", "MEDIUM"),
    ("submit", "səbˈmɪt", "v. 提交；服从", "verb", "MEDIUM"),
    ("substance", "ˈsʌbstəns", "n. 物质；实质", "noun", "MEDIUM"),
    ("substitute", "ˈsʌbstɪtuːt", "n. 替代品 v. 替代", "noun", "MEDIUM"),
    ("succeed", "səkˈsiːd", "v. 成功；继承", "verb", "EASY"),
    ("sufficient", "səˈfɪʃnt", "adj. 足够的", "adj", "MEDIUM"),
    ("suitable", "ˈsuːtəbl", "adj. 合适的", "adj", "MEDIUM"),
    ("summarize", "ˈsʌməraɪz", "v. 总结；概括", "verb", "MEDIUM"),
    ("superior", "suːˈpɪriər", "adj. 优越的；上级的", "adj", "MEDIUM"),
    ("supply", "səˈplaɪ", "v. 供应 n. 供给", "verb", "MEDIUM"),
    ("support", "səˈpɔːrt", "v. 支持 n. 支持", "verb", "EASY"),
    ("suppose", "səˈpoʊz", "v. 假设；猜想", "verb", "MEDIUM"),
    ("surround", "səˈraʊnd", "v. 包围；环绕", "verb", "MEDIUM"),
    ("survive", "sərˈvaɪv", "v. 幸存；生存", "verb", "MEDIUM"),
    ("suspect", "səˈspekt", "v. 怀疑 n. 嫌疑人", "verb", "MEDIUM"),
    ("suspend", "səˈspend", "v. 暂停；悬挂", "verb", "MEDIUM"),
    ("sustain", "səˈsteɪn", "v. 维持；支撑", "verb", "MEDIUM"),
    ("symbol", "ˈsɪmbl", "n. 象征；符号", "noun", "MEDIUM"),
    ("sympathy", "ˈsɪmpəθi", "n. 同情；慰问", "noun", "MEDIUM"),
    ("system", "ˈsɪstəm", "n. 系统；制度", "noun", "EASY"),

    # ===== T =====
    ("talent", "ˈtælənt", "n. 天赋；才能", "noun", "MEDIUM"),
    ("target", "ˈtɑːrɡɪt", "n. 目标 v. 瞄准", "noun", "MEDIUM"),
    ("temporary", "ˈtempəreri", "adj. 临时的", "adj", "MEDIUM"),
    ("tend", "tend", "v. 倾向；照料", "verb", "MEDIUM"),
    ("tension", "ˈtenʃn", "n. 紧张；张力", "noun", "MEDIUM"),
    ("terminal", "ˈtɜːrmɪnl", "n. 终端；终点站 adj. 末期的", "noun", "HARD"),
    ("theory", "ˈθɪri", "n. 理论；学说", "noun", "MEDIUM"),
    ("threat", "θret", "n. 威胁", "noun", "MEDIUM"),
    ("tolerate", "ˈtɑːləreɪt", "v. 容忍", "verb", "MEDIUM"),
    ("trace", "treɪs", "v. 追踪 n. 痕迹", "verb", "MEDIUM"),
    ("tradition", "trəˈdɪʃn", "n. 传统", "noun", "EASY"),
    ("transfer", "trænsˈfɜːr", "v. 转移；调动", "verb", "MEDIUM"),
    ("transform", "trænsˈfɔːrm", "v. 转变；改造", "verb", "MEDIUM"),
    ("transition", "trænˈzɪʃn", "n. 过渡；转变", "noun", "HARD"),
    ("translate", "trænsˈleɪt", "v. 翻译", "verb", "MEDIUM"),
    ("transport", "trænsˈpɔːrt", "v. 运输 n. 交通", "verb", "MEDIUM"),
    ("treat", "triːt", "v. 对待；治疗", "verb", "EASY"),
    ("trend", "trend", "n. 趋势；潮流", "noun", "MEDIUM"),
    ("trigger", "ˈtrɪɡər", "v. 引发 n. 扳机", "verb", "MEDIUM"),
    ("typical", "ˈtɪpɪkl", "adj. 典型的", "adj", "MEDIUM"),

    # ===== U =====
    ("ultimate", "ˈʌltɪmət", "adj. 最终的；根本的", "adj", "MEDIUM"),
    ("undergo", "ˌʌndərˈɡoʊ", "v. 经历；经受", "verb", "MEDIUM"),
    ("undertake", "ˌʌndərˈteɪk", "v. 承担；从事", "verb", "MEDIUM"),
    ("unique", "juˈniːk", "adj. 独特的；唯一的", "adj", "MEDIUM"),
    ("universal", "ˌjuːnɪˈvɜːrsl", "adj. 普遍的；通用的", "adj", "MEDIUM"),
    ("urban", "ˈɜːrbən", "adj. 城市的", "adj", "MEDIUM"),
    ("urge", "ɜːrdʒ", "v. 敦促 n. 强烈欲望", "verb", "MEDIUM"),
    ("utilize", "ˈjuːtəlaɪz", "v. 利用", "verb", "MEDIUM"),

    # ===== V =====
    ("valid", "ˈvælɪd", "adj. 有效的；正当的", "adj", "MEDIUM"),
    ("vanish", "ˈvænɪʃ", "v. 消失", "verb", "MEDIUM"),
    ("variety", "vəˈraɪəti", "n. 多样性；种类", "noun", "MEDIUM"),
    ("various", "ˈveriəs", "adj. 各种各样的", "adj", "EASY"),
    ("venture", "ˈventʃər", "n. 风险投资 v. 冒险", "noun", "MEDIUM"),
    ("verify", "ˈverɪfaɪ", "v. 核实；验证", "verb", "MEDIUM"),
    ("victim", "ˈvɪktɪm", "n. 受害者", "noun", "MEDIUM"),
    ("violate", "ˈvaɪəleɪt", "v. 违反；侵犯", "verb", "MEDIUM"),
    ("virtue", "ˈvɜːrtʃuː", "n. 美德；优点", "noun", "MEDIUM"),
    ("visible", "ˈvɪzəbl", "adj. 可见的", "adj", "MEDIUM"),
    ("vital", "ˈvaɪtl", "adj. 至关重要的", "adj", "MEDIUM"),
    ("voluntary", "ˈvɑːlənteri", "adj. 自愿的", "adj", "MEDIUM"),
    ("vulnerable", "ˈvʌlnərəbl", "adj. 脆弱的；易受伤害的", "adj", "HARD"),

    # ===== W =====
    ("welfare", "ˈwelfer", "n. 福利；幸福", "noun", "MEDIUM"),
    ("widespread", "ˈwaɪdspred", "adj. 广泛的", "adj", "MEDIUM"),
    ("witness", "ˈwɪtnəs", "n. 目击者 v. 目睹", "noun", "MEDIUM"),
    ("worthwhile", "ˌwɜːrθˈwaɪl", "adj. 值得的", "adj", "MEDIUM"),
]


def esc(s: str) -> str:
    return s.replace("'", "''")


def build_sql() -> str:
    buf = io.StringIO()
    buf.write("-- 批量灌入四六级高频单词（自动生成）\n")
    buf.write("BEGIN;\n\n")
    for w, ph, df, pos, diff in WORDS:
        buf.write(
            "INSERT INTO word (word, phonetic, definition, part_of_speech, difficulty_level, created_at, updated_at) "
            f"SELECT '{esc(w)}', '{esc(ph)}', '{esc(df)}', '{pos}', '{diff}', NOW(), NOW() "
            f"WHERE NOT EXISTS (SELECT 1 FROM word WHERE word = '{esc(w)}');\n"
        )
    buf.write("\nCOMMIT;\n")
    buf.write("\nSELECT 'total words now: ' || COUNT(*) FROM word;\n")
    return buf.getvalue()


if __name__ == "__main__":
    sql = build_sql()
    out_path = "scripts/seed_words.sql"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(sql)
    print(f"generated {len(WORDS)} words -> {out_path}")
